apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-stack
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/christianh814/kargo-stack-sample-deployment
      revision: main
      directories:
      - path: applications/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/christianh814/kargo-stack-sample-deployment
        targetRevision: main
        path: '{{ path }}'
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
