apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Only skips dry run when resource is NOT there. Helpful for bootstrapping
## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

helmCharts:
- name: argo-rollouts
  repo: https://argoproj.github.io/argo-helm
  version: 2.35.0
  valuesFile: argo-rollouts-values.yaml
  releaseName: argo-rollouts
  namespace: argo-rollouts

resources:
- ns.yaml
